### ISSUE TITLE
Default setup w/ redis not working (Windows)

### ISSUE THREAD

**Issue by batjko** [apparatus/fuge#12]
Hi guys,

I have just followed the instructions in the README, i.e. installed fuse globally, generated the scaffold, then started it with `fuge run ./fuge/compose-dev.yml`.

During the scaffolding, I selected redis as the communication mechanism, for both of the default services.

This is on Windows 7, 64bit.

The errors below indicate an issue with the redis transport layer. The whole thing went a little fast so I can only surmise that the redis docker container wasn't downloaded properly? 

```shell
> fuge run ./fuge/compose-dev.yml
compiling...
starting proxy...
  proxy frontend 10000 -> 10.80.99.23:20000
  proxy service1 10001 -> 10.80.99.23:20001
  proxy service2 10002 -> 10.80.99.23:20002
running: frontend
running: service1
running: service2
running: __proxy
[service2 - 6604]: 2016-01-28T09:06:35.222Z uw9y8dlaklfo/1453971995207/3108/- INFO      hello   Seneca/0.7.2/uw9y8dlaklfo/1453971995207/3108/-
[service1 - 10472]: 2016-01-28T09:06:35.239Z mpqkftac8swp/1453971995207/10152/- INFO    hello   Seneca/0.7.2/mpqkftac8swp/1453971995207/10152/-
[frontend - 11324]: 2016-01-28T09:06:35.550Z 66urhk3syiy2/1453971995519/6376/- INFO     hello   Seneca/0.7.2/66urhk3syiy2/1453971995519/6376/-
[service2 - 6604]: 2016-01-28T09:06:35.597Z uw9y8dlaklfo/1453971995207/3108/- INFO      listen  {type:redis-queue,pin:role:db,cmd:*}
[service1 - 10472]: 2016-01-28T09:06:35.613Z mpqkftac8swp/1453971995207/10152/- INFO    listen  {type:redis-queue,pin:role:db,cmd:*}
[service2 - 6604]: 2016-01-28T09:06:35.628Z uw9y8dlaklfo/1453971995207/3108/- INFO      plugin  redis-queue-transport   ACT
0nqaqjbtovi8/4iaacxe1ih9h       hook:listen,role:transport,type:redis-queue     listen  open    {timeout:10556,type:redis-queue,host:localhost,port:6379,pin:role:db,cmd:*,msgprefix:seneca_,callmax:111111,msg        {did:(wuy8k),fixedargs:{},context:{}}
[service1 - 10472]: 2016-01-28T09:06:35.644Z mpqkftac8swp/1453971995207/10152/- INFO    plugin  redis-queue-transport   ACT
bts0f3fxccyz/0e660z758mi0       hook:listen,role:transport,type:redis-queue     listen  open    {timeout:10556,type:redis-queue,host:localhost,port:6379,pin:role:db,cmd:*,msgprefix:seneca_,callmax:111111,msg        {did:(5tt3b),fixedargs:{},context:{}}
[frontend - 11324]: 2016-01-28T09:06:35.784Z 66urhk3syiy2/1453971995519/6376/- INFO     client  {host:127.0.0.1,port:10001,pin:{role:service1}}
[frontend - 11324]: 2016-01-28T09:06:35.784Z 66urhk3syiy2/1453971995519/6376/- INFO     client  {host:127.0.0.1,port:10002,pin:{role:service2}}
[frontend - 11324]: listening on port: 20000
[service2 - 6604]: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at RedisClient.on_error (c:\Git\fuge-test\service2\node_modules\seneca-redis-queue-transport\node_modules\redis\index.js:196:24)
    at Socket.<anonymous> (c:\Git\fuge-test\service2\node_modules\seneca-redis-queue-transport\node_modules\redis\index.js:106:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)
[service1 - 10472]: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at RedisClient.on_error (c:\Git\fuge-test\service1\node_modules\seneca-redis-queue-transport\node_modules\redis\index.js:196:24)
    at Socket.<anonymous> (c:\Git\fuge-test\service1\node_modules\seneca-redis-queue-transport\node_modules\redis\index.js:106:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)
process exit [6604]: service2
process exit [10472]: service1
```
I don't want to add too much noise, but let me know if you want me to also post the contents of the three log files (frontend, service1 and service2).

Any idea what went wrong?

**Comment by batjko** [comment]
Actually, never mind. I just saw that this doesn't happen automatically and I'm supposed to get the redis container myself.

That didn't work either, i.e. `docker pull redis` failed with this error:
```shell
An error occurred trying to connect: Post http://localhost:2375/v1.21/images/create?fromImage=redis%3Alatest: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.
```

But I then started from scratch without redis and that went fine as far as I can see.

**Comment by batjko** [comment]
Ok well, got excited too quickly. 
While using the http method didn't produce any errors (i.e. all three processes seem to be running fine), actually accessing the frontend via the browser produces another connection refused error:

```shell
> fuge shell ./fuge/compose-dev.yml
compiling...
starting proxy...
  proxy frontend 10000 -> 10.80.99.23:20000
  proxy service1 10001 -> 10.80.99.23:20001
  proxy service2 10002 -> 10.80.99.23:20002
starting shell..
? fuge> client error: 10000 -> 10.80.99.23:20000 => ECONNREFUSED
please retry operation
client error: 10000 -> 10.80.99.23:20000 => ECONNREFUSED
please retry operation
```

I get the feeling Windows support is still a little rough around the edges.

**Comment by mcollina** [comment]
@batjko thanks for testing this on Windows. You are right, Windows support is definitely not on par. We'll have a look and we'll get this fixed.

There seem to be an issue with the proxy.

**Comment by pelger** [comment]
Have published an update with improved windows support. Also I have removed the redis support for now as this was not working correctly. If you could please upgrade, generate a fresh system and let us know if this is now working for you on windows, that would be awesome!

**Comment by batjko** [comment]
Yup, that seems to have done the trick.
Updated fuge, generated a new system (I wasn't asked anymore whether to use http or redis), and localhost:10000 gives me the expected page. The services are up and produce proper output.

I'm happy to close the issue, even though Redis isn't working but since that's essentially descoped now that's fine.

**Comment by pelger** [comment]
Awesome - thanks!
