### ISSUE TITLE
fuge generate system - error

### ISSUE THREAD

**Issue by knito** [apparatus/fuge#123]
Hi there,

I just download fuge through npm

`npm install fuge -g`

That happened with no problem, but when I try to create the scafolding the project, it is thrown an exception:

```
$ fuge generate system
pulling...
Error: could not parse github url: system
    at Object.generate (/usr/local/lib/node_modules/fuge/node_modules/fuge-runner/lib/gitPuller.js:73:19)
    at Object.generate (/usr/local/lib/node_modules/fuge/node_modules/fuge-runner/runner.js:33:47)
    at Object.generateRepo (/usr/local/lib/node_modules/fuge/runner.js:61:12)
    at Command.generateRepo [as func] (/usr/local/lib/node_modules/fuge/fuge.js:64:19)
    at Command.call (/usr/local/lib/node_modules/fuge/node_modules/commist/index.js:100:8)
    at Object.parse (/usr/local/lib/node_modules/fuge/node_modules/commist/index.js:58:19)
    at start (/usr/local/lib/node_modules/fuge/fuge.js:131:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/fuge/fuge.js:138:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
$ 

```

Reading the code, it is expecting a url for a github repository but that is not defined in anyplace.

Could you please help me with that?

Thanks,
Alejandro.

**Comment by mihaidma** [comment]
@knito the fuge generate now it is cloning from any valid github url (including **user/github_repo** format), we removed the previous functionality that was generating a project boilerplate.

The format is specified in the documentation README in the Fuge commands section:
`fuge generate <Github repo> - clone a Github repo, supports all valid repo name formats`

Please reopen if you need more help.

I'll add code to handle this error.

**Comment by knito** [comment]
@mihaidma, 

Thanks for your answer. What repo should I clone to mimic the getting started process described in the animated image?

Many thanks in advance.

**Comment by mcdonnelldean** [comment]
@knito Right now the we don't have suggested repo's. Expect them in two weeks. We found some bugs in the generated code, which needs time to fix. 

As a workaround https://github.com/nodezoo/nodezoo-npm is a nice module to copy. You will have to clean it down but it shows how a 'correct' seneca service should look.

**Comment by knito** [comment]
Thanks a lot for your quick response!
