### ISSUE TITLE
Error: could not parse github url: system [fuge generate system]

### ISSUE THREAD

**Issue by vforv** [apparatus/fuge#150]
Here is the error I get when I try: `fuge generate system`:

```
pulling...
Error: could not parse github url: system
    at Object.generate (/usr/lib/node_modules/fuge/node_modules/fuge-runner/lib/gitPuller.js:73:19)
    at Object.generate (/usr/lib/node_modules/fuge/node_modules/fuge-runner/runner.js:33:47)
    at Object.cloneRepo (/usr/lib/node_modules/fuge/runner.js:57:12)
    at Command.cloneRepo [as func] (/usr/lib/node_modules/fuge/fuge.js:60:19)
    at Command.call (/usr/lib/node_modules/fuge/node_modules/commist/index.js:100:8)
    at Object.parse (/usr/lib/node_modules/fuge/node_modules/commist/index.js:58:19)
    at start (/usr/lib/node_modules/fuge/fuge.js:122:27)
    at Object.<anonymous> (/usr/lib/node_modules/fuge/fuge.js:129:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
master@master-MS-7798:~/Documents/microservices$ 

```

Any solution for this?

Thanks

**Comment by mihaidma** [comment]
`fuge generate` is an alias for `fuge clone`, and will be deprecated. It tries to clone the github repo that you specified.

**Comment by vforv** [comment]
Aha, how can I generate this structure with fuge?

```
├── fuge
│   ├── compose-dev.yml
│   ├── docker-compose.yml
│   └── fuge-config.json
├── service1
│   └── Dockerfile
├── service2
│   └── Dockerfile
└── api
│   └── Dockerfile
├── static
└   └── Dockerfile
```

**Comment by mihaidma** [comment]
The generate function is deprecated and replaced with clone functionality.
I'll close this issue.

**Comment by vforv** [comment]
Is it possible to use clone to get structure above? If it is what I need to type?

**Comment by mihaidma** [comment]
for clone you have to pass any valid github url and it will clone that repo
