### ISSUE TITLE
watch all bug

### ISSUE THREAD

**Issue by vforv** [apparatus/fuge#164]
When I try do watch all getting error:

```
fuge> [apigateway] file change: has-ansi
/usr/lib/node_modules/fuge/node_modules/fuge-runner/lib/system.js:134
      util.streamOutput(container, _system.global.log_path)
                                          ^

TypeError: Cannot read property 'global' of undefined
    at /usr/lib/node_modules/fuge/node_modules/fuge-runner/lib/system.js:134:43
    at run (/usr/lib/node_modules/fuge/node_modules/fuge-runner/lib/support/processRunner.js:90:5)
    at Object.start (/usr/lib/node_modules/fuge/node_modules/fuge-runner/lib/support/processRunner.js:97:7)
    at Object.start (/usr/lib/node_modules/fuge/node_modules/fuge-runner/lib/commands/run.js:30:29)
    at startContainer (/usr/lib/node_modules/fuge/node_modules/fuge-runner/lib/system.js:126:12)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/fuge/node_modules/fuge-runner/lib/system.js:79:9)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/fuge/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/usr/lib/node_modules/fuge/node_modules/chokidar/index.js:238:5)

```

**Comment by pelger** [comment]
Thanks for the report - will get back to you shortly
