### ISSUE TITLE
fuge generate system should accept the name of a folder

### ISSUE THREAD

**Issue by AdrianRossouw** [apparatus/fuge#21]
I was in a folder that had a checkout of the fuge repo, and i tried to create a new folder to test with, but I got this instead.

``````
Sikozu:nearform adrian$ fuge generate system fuge-test
fs.js:842
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir '/Users/adrian/Projects/nearform/fuge'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Object.generateSystem (/Users/adrian/.nvm/versions/node/v5.3.0/lib/node_modules/fuge/generator.js:425:8)
    at Command.generateSystem [as func] (/Users/adrian/.nvm/versions/node/v5.3.0/lib/node_modules/fuge/fuge.js:43:15)
    at Command.call (/Users/adrian/.nvm/versions/node/v5.3.0/lib/node_modules/fuge/node_modules/commist/index.js:100:8)
    at Object.parse (/Users/adrian/.nvm/versions/node/v5.3.0/lib/node_modules/fuge/node_modules/commist/index.js:58:19)
    at start (/Users/adrian/.nvm/versions/node/v5.3.0/lib/node_modules/fuge/fuge.js:145:27)
    at Object.<anonymous> (/Users/adrian/.nvm/versions/node/v5.3.0/lib/node_modules/fuge/fuge.js:153:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    ```
``````

**Comment by lucamaraschi** [comment]
I believe we can close it as it was merged with #92
