### ISSUE TITLE
Dash in service names causes build failures

### ISSUE THREAD

**Issue by brainling** [apparatus/fuge#38]
If I generate a service with a dash in the name, lets say my-service, and then do a fuge build, I will get the following error:

containers:107
exports.my-service = {
^^^^^^^^^^^^^^^^^^^^^^^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at requireFromString (/usr/lib/node_modules/fuge/node_modules/xeno-compiler/compile.js:30:7)
    at Object.compile (/usr/lib/node_modules/fuge/node_modules/xeno-compiler/compile.js:274:15)
    at Object.compile (/usr/lib/node_modules/fuge/node_modules/xeno-compiler/main.js:23:9)
    at /usr/lib/node_modules/fuge/node_modules/xenotype/xeno.js:26:16
    at Object.translate (/usr/lib/node_modules/fuge/node_modules/xeno-compose/compose.js:245:5)
    at Object.compile (/usr/lib/node_modules/fuge/node_modules/xenotype/xeno.js:24:13)
    at Object.compile (/usr/lib/node_modules/fuge/util.js:76:10)
    at Command.buildSystem [as func] (/usr/lib/node_modules/fuge/fuge.js:68:8)

Obviously some code Fuge is generating is create that JavaScript error. I can fix it by hand by editing my compose-dev.yml to replace 'my-service' with 'myService' as the top level element, but it would be nice of the Fuge generator system could handle this. Either remove the dash and camel case the service name in the compose files, or make the code generator create JavaScript legal code for the export blocks (e.g. exports['my-service'] = {}).

**Comment by AdrianRossouw** [comment]
I think there were limitations inherited from nscale related to this. 

@pelger Is this is a [xeno-compose](https://github.com/apparatus/xeno-compose) issue, related to how it uses eval to generate the backwards compatible data structure?

I would not try to fudge service names, because that can be a lossy operation (ie: it can break when you try to unfudge it). It's best to be explicit about it.

@brainling thanks for reporting this. Perhaps avoid using dashes in names for now? underscores should work, unless those are invalid in docker-compose files.

**Comment by brainling** [comment]
For now I just use the work around of editing my compose-dev.yml to remove the underscore from the top level element, like so:
`lineConsumer:
  build: ../line-consumer/
  container_name: line-consumer`

And that works fine...this is definitely not a show stopper issue for me, won't stop me from using Fuge, just a minor annoyance I noticed. Thanks for the suggestion :)

**Comment by mcdonnelldean** [comment]
@brainling Just from my own usage, I ended up not using them, the problem happens when you start adding config in fuge-config. Because js doesn't handle them without stringifying the name it ends up as a mishmash of _ and -. In the end I just went _ everywhere.
