### ISSUE TITLE
Udp port mapping not supported

### ISSUE THREAD

**Issue by mcollina** [apparatus/fuge#51]
Given:
```
baseswim:
  image: matteocollina/baseswim
  ports:
    - 7799:7799/udp
    - 3000:3000
```

This results in this error:
```
ReferenceError: udp is not defined
    at Object.<anonymous> (containers:43:24)
    at Module._compile (module.js:435:26)
    at requireFromString (/Users/matteo/.nvm/versions/node/v4.2.4/lib/node_modules/fuge/node_modules/xenotype/node_modules/xeno-compiler/compile.js:30:7)
    at Object.compile (/Users/matteo/.nvm/versions/node/v4.2.4/lib/node_modules/fuge/node_modules/xenotype/node_modules/xeno-compiler/compile.js:274:15)
    at Object.compile (/Users/matteo/.nvm/versions/node/v4.2.4/lib/node_modules/fuge/node_modules/xenotype/node_modules/xeno-compiler/main.js:23:9)
    at /Users/matteo/.nvm/versions/node/v4.2.4/lib/node_modules/fuge/node_modules/xenotype/xeno.js:26:16
    at Object.translate (/Users/matteo/.nvm/versions/node/v4.2.4/lib/node_modules/fuge/node_modules/xenotype/node_modules/xeno-compose/compose.js:245:5)
    at Object.compile (/Users/matteo/.nvm/versions/node/v4.2.4/lib/node_modules/fuge/node_modules/xenotype/xeno.js:24:13)
    at Object.compile (/Users/matteo/.nvm/versions/node/v4.2.4/lib/node_modules/fuge/util.js:76:10)
    at Command.runShell [as func] (/Users/matteo/.nvm/versions/node/v4.2.4/lib/node_modules/fuge/fuge.js:98:8)
```

**Comment by mcdonnelldean** [comment]
This would be super awesome, It would allow me to run premade metrics containers too (since they all communicate over UDP).
