### ISSUE TITLE
fuge system generate fails on node 0.10 in interactive mode on OS X

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/fuge#8]
this works fine on 0.12+ but on 0.10 it throws an error, 
this is due to `prompt-sync`  attempts to interact with /dev/stdin
issue here: https://github.com/0xxff/prompt-sync/issues/8

```sh
$ node --version
v0.10.40
$ fuge gen sys
? System transport (http, redis, mixed):
fs.js:488
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EAGAIN, resource temporarily unavailable
    at Object.fs.readSync (fs.js:488:19)
    at Object.prompt (/Users/davidclements/z/nearForm/fuge/fuge/node_modules/prompt-sync/index.js:54:15)
    at incite (/Users/davidclements/z/nearForm/fuge/fuge/node_modules/incite/index.js:11:20)
    at transportSelection (/Users/davidclements/z/nearForm/fuge/fuge/generator.js:86:21)
    at Object.generateSystem (/Users/davidclements/z/nearForm/fuge/fuge/generator.js:322:7)
    at Command.generateSystem [as func] (/Users/davidclements/z/nearForm/fuge/fuge/fuge.js:27:15)
    at Command.call (/Users/davidclements/z/nearForm/fuge/fuge/node_modules/commist/index.js:100:8)
    at Object.parse (/Users/davidclements/z/nearForm/fuge/fuge/node_modules/commist/index.js:58:19)
    at start (/Users/davidclements/z/nearForm/fuge/fuge/fuge.js:113:27)
    at Object.<anonymous> (/Users/davidclements/z/nearForm/fuge/fuge/fuge.js:119:3)
```

**Comment by davidmarkclements** [comment]
solved from update of incite and positive deps (which moved from `sync-prompt` to https://github.com/davidmarkclements/syncoprompt)
